version: 1
default_environment: dev
project_id: e622fd24-e413-4240-8b1d-3e9b141d953e
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
    config:
      files:
      - "[{'entity': 'order_details','path': '../data/order_details.csv','keys': ['order_id','product_id'],}]"
  - name: tap-postgres
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-postgres.git
    config:
      host: localhost
      port: 44444
      database: northwind
      user: northwind_user
  loaders:
  - name: target-postgres
    variant: meltanolabs
    pip_url: meltanolabs-target-postgres
  - name: target-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/target-csv.git
    config:
      destination_path: ../data/csv/ano-mes-dia/
jobs:
- name: pipeline_extracao_local_csv
  tasks:
  - tap-csv target-csv
- name: pipeline_extracao_local_postgres
  tasks:
  - tap-postgres target-csv
